import type { Metadata } from 'next';
import { DM_Sans, Poppins } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import LeftSection from '@/components/layout/LeftSection';
import MiddleSection from '@/components/layout/MiddleSection';
import RightSection from '@/components/layout/RightSection';
import Ribbon from '@/components/layout/Ribbon';
import { Suspense } from 'react';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  preload: true,
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Solar Saathi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${poppins.variable} bg-background-dark-500 fixed inset-0 antialiased`}
      >
        <ReactQueryProvider>
          <div className="pointer-events-none absolute inset-x-12 top-[51px] bottom-[90px] z-[1000] flex gap-6">
            <Suspense fallback={null}>
              <LeftSection />
              <MiddleSection />
              <RightSection />
            </Suspense>
          </div>
          {children}
          <Ribbon />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
